execute pathogen#infect()
filetype plugin indent on

" Key remaps
let mapleader = " "
inoremap jk <Esc>
nnoremap <leader>l :bnext!<CR>
nnoremap <leader>h :bprev!<CR>

" Undo
set undofile
set undodir=~/.vim/undo
set undolevels=1000
set undoreload=10000


" Colors
colorscheme base16-solarized-dark
let g:solarized_termtrans=1
let g:solarized_termcolors=256
let g:airline_theme='solarized'
set background=dark
syntax on
highlight Pmenu ctermbg=gray ctermfg=black
highlight PmenuSel ctermbg=darkgray ctermfg=black

" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
